export enum Configuration {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',

  // postgres config
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  JWT_SECRET = 'JWT_SECRET',
}
